const legend = {
"en":"Thanks for using iframe to watch YouTube video with minimal and quiet advertisement. The following link starts with youtube id",
"zh-CN":"感谢您使用 iframe 以最少且安静的广告观看 YouTube 视频。以下链接以 youtube id 开头",
"zh-HK":"感謝您使用 iframe 以最少且安靜的廣告觀看 YouTube 視頻。以下鏈接以 youtube id 開頭",
"zh-TW":"感謝您使用 iframe 以最少且安靜的廣告觀看 YouTube 視頻。以下鏈接以 youtube id 開頭",
"ja":"最小限の静かな広告でYouTubeビデオを視聴するためにiframeを使用していただきありがとうございます。次のリンクはyoutube idで始まります",
"ko":"iframe을 사용하여 최소한의 조용한 광고로 YouTube 동영상을 시청해주셔서 감사합니다. 다음 링크는 youtube id로 시작합니다.",
"ru":"Благодарим за использование iframe для просмотра видео на YouTube с минимальной и тихой рекламой. Следующая ссылка начинается с идентификатора YouTube",
"fr":"Merci d'avoir utilisé iframe pour regarder une vidéo YouTube avec une publicité minimale et silencieuse. Le lien suivant commence par l'identifiant youtube",
"th":"ขอบคุณที่ใช้ iframe เพื่อดูวิดีโอ YouTube ที่มีโฆษณาน้อยที่สุดและเงียบ ลิงค์ต่อไปนี้ขึ้นต้นด้วย youtube id",
"nl":"Bedankt voor het gebruik van iframe om YouTube-video's te bekijken met minimale en stille advertenties. De volgende link begint met youtube id",
"it":"Grazie per aver utilizzato iframe per guardare i video di YouTube con pubblicità minima e silenziosa. Il seguente link inizia con l'id di YouTube",
"ml":"കുറഞ്ഞതും നിശബ്ദവുമായ പരസ്യത്തോടെ YouTube വീഡിയോ കാണാൻ iframe ഉപയോഗിച്ചതിന് നന്ദി. ഇനിപ്പറയുന്ന ലിങ്ക് യൂട്യൂബ് ഐഡിയിൽ തുടങ്ങുന്നു",
"la":"Thanks for using iframe to watch YouTube video with minimal and quiet advertisement. Vinculum sequens incipit cum YouTube id",
"pt":"Obrigado por usar iframe para assistir a vídeos do YouTube com publicidade mínima e silenciosa. O seguinte link começa com o id do youtube",
"pl":"Dziękujemy za użycie iframe do oglądania filmów na YouTube z minimalną i cichą reklamą. Poniższy link zaczyna się od identyfikatora youtube",
"cs":"Děkujeme, že používáte iframe ke sledování videa YouTube s minimální a tichou reklamou. Následující odkaz začíná youtube id",
"es":"Gracias por usar iframe para ver videos de YouTube con publicidad mínima y silenciosa. El siguiente enlace comienza con la identificación de youtube",
"de":"Vielen Dank, dass Sie iframe verwenden, um YouTube-Videos mit minimaler und leiser Werbung anzusehen. Der folgende Link beginnt mit der YouTube-ID",
"sv":"Tack för att du använder iframe för att titta på YouTube -video med minimal och tyst reklam. Följande länk börjar med youtube -id",
"el":"Σας ευχαριστούμε που χρησιμοποιήσατε το iframe για να παρακολουθήσετε βίντεο στο YouTube με ελάχιστη και αθόρυβη διαφήμιση. Ο παρακάτω σύνδεσμος ξεκινά με το αναγνωριστικό του youtube",
"hi":"कम से कम और शांत विज्ञापन के साथ YouTube वीडियो देखने के लिए iframe का उपयोग करने के लिए धन्यवाद। निम्न लिंक यूट्यूब आईडी से शुरू होता है",
"id":"Terima kasih telah menggunakan iframe untuk menonton video YouTube dengan iklan minimal dan senyap. Tautan berikut dimulai dengan id youtube",
"lo":"ຂອບໃຈທີ່ໃຊ້ iframe ເພື່ອເບິ່ງວິດີໂອ YouTube ດ້ວຍການໂຄສະນາ ໜ້ອຍ ທີ່ສຸດແລະງຽບສະຫງົບ. ລິ້ງຕໍ່ໄປນີ້ເລີ່ມຕົ້ນດ້ວຍ id youtube",
"fi":"Kiitos, että käytit iframea YouTube -videon katsomiseen minimaalisella ja hiljaisella mainoksella. Seuraava linkki alkaa youtuben tunnuksella",
"ne":"न्यूनतम र शान्त विज्ञापन संग YouTube भिडियो हेर्न iframe को लागी धन्यवाद। निम्न लि you्क youtube id बाट सुरु हुन्छ",
"tr":"Minimum ve sessiz reklamlarla YouTube videosunu izlemek için iframe kullandığınız için teşekkür ederiz. Aşağıdaki bağlantı youtube kimliği ile başlar",
"vi":"Cảm ơn bạn đã sử dụng iframe để xem video YouTube với quảng cáo tối thiểu và yên tĩnh. Liên kết sau bắt đầu bằng id youtube"
};

